# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Onboardbasekit < Formula
  desc ""
  homepage "https://github.com/Onboardbase/onboardbasekit"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Onboardbase/onboardbasekit/releases/download/v0.0.4/onboardbasekit_Darwin_arm64.tar.gz"
      sha256 "029661d4d944513947d365ba62f506ba8686a7bd45933e0e88170c45d807bca7"

      def install
        bin.install "onboardbasekit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Onboardbase/onboardbasekit/releases/download/v0.0.4/onboardbasekit_Darwin_x86_64.tar.gz"
      sha256 "c6350d5602df367204a84b08bf21dc641690e437c37aa67218493a31dc577a25"

      def install
        bin.install "onboardbasekit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Onboardbase/onboardbasekit/releases/download/v0.0.4/onboardbasekit_Linux_arm64.tar.gz"
      sha256 "747461bb27c3cccc29b4f12aab974c019489f7ff0d90dcf20acf441953347f3e"

      def install
        bin.install "onboardbasekit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Onboardbase/onboardbasekit/releases/download/v0.0.4/onboardbasekit_Linux_x86_64.tar.gz"
      sha256 "371221fd478713ffffcf30a82b394867020da6179231cb6260d8dd1cb857ea8a"

      def install
        bin.install "onboardbasekit"
      end
    end
  end
end
