# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Onboardbasekit < Formula
  desc ""
  homepage "https://github.com/Onboardbase/onboardbasekit"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Onboardbase/onboardbasekit/releases/download/v1.0.1/onboardbasekit_Darwin_arm64.tar.gz"
      sha256 "39c4044460da9c35d65add8e3fc6c76df0a10754f5115d947737246958fa5343"

      def install
        bin.install "onboardbasekit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Onboardbase/onboardbasekit/releases/download/v1.0.1/onboardbasekit_Darwin_x86_64.tar.gz"
      sha256 "48c1b859cdd9f9a61465331c422bd322a5b8f4a5b16ad9542c659eba38bbf418"

      def install
        bin.install "onboardbasekit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Onboardbase/onboardbasekit/releases/download/v1.0.1/onboardbasekit_Linux_arm64.tar.gz"
      sha256 "85500438d5d8754c742f644850cd5ab143f0afa965d56e6e0205e57050e6e084"

      def install
        bin.install "onboardbasekit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Onboardbase/onboardbasekit/releases/download/v1.0.1/onboardbasekit_Linux_x86_64.tar.gz"
      sha256 "b335395b804100e5d59588f988b5cc9e96bf15a81125249d26cabf8083e88756"

      def install
        bin.install "onboardbasekit"
      end
    end
  end
end
