# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Startkit < Formula
  desc ""
  homepage "https://github.com/Onboardbase/startkit"
  version "1.0.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Onboardbase/startkit/releases/download/v1.0.12/startkit_Darwin_x86_64.tar.gz"
      sha256 "160b36d77cfef2e25e13990530eeadba3d578c7acc4c06c0d4b089322073f613"

      def install
        bin.install "startkit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Onboardbase/startkit/releases/download/v1.0.12/startkit_Darwin_arm64.tar.gz"
      sha256 "33a38454f29ed5bdeac3e23f9ce9b4372e7250bc8f79fb8127017d674a61c03a"

      def install
        bin.install "startkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Onboardbase/startkit/releases/download/v1.0.12/startkit_Linux_arm64.tar.gz"
      sha256 "73a3b51350d964ddd0bbf726113eeba33e71b99cffac380404cf0c7e2ab625fb"

      def install
        bin.install "startkit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Onboardbase/startkit/releases/download/v1.0.12/startkit_Linux_x86_64.tar.gz"
      sha256 "f2ab9e1be0a854ec7cefbc290860a0ee7d5e2255196f85e991e10b7007602679"

      def install
        bin.install "startkit"
      end
    end
  end
end
