# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Startkit < Formula
  desc ""
  homepage "https://github.com/Onboardbase/startkit"
  version "1.0.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Onboardbase/startkit/releases/download/v1.0.13/startkit_Darwin_x86_64.tar.gz"
      sha256 "beb18745aca4ddd2b0b3fcbddf717c47d1bf4797843462b0f8a7c1a92dd74cf9"

      def install
        bin.install "startkit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Onboardbase/startkit/releases/download/v1.0.13/startkit_Darwin_arm64.tar.gz"
      sha256 "9b8b4331e20d7a1d81e79c77643afc7d7d2091ffcf779b880c48d55c92f69169"

      def install
        bin.install "startkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Onboardbase/startkit/releases/download/v1.0.13/startkit_Linux_x86_64.tar.gz"
      sha256 "01b44b9e315170c922402e3e608b7e28dd411107d55f97a0cc1240dc819c7ced"

      def install
        bin.install "startkit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Onboardbase/startkit/releases/download/v1.0.13/startkit_Linux_arm64.tar.gz"
      sha256 "152f730976e25886289db0f39b2488743aa93606689789a1eb27d641423b68fe"

      def install
        bin.install "startkit"
      end
    end
  end
end
